### ISSUE TITLE
Any plans to have support of the Redshift syntax?

### ISSUE THREAD

**Issue by unicast** [markdrago/pgsanity#21]
Any way I can contribute?

**Comment by markdrago** [comment]
So, the way pgsanity works it isn't actually doing any of the validation itself.  It's leveraging ecpg which comes with postgresql.  As far as I know there isn't a great way to add redshift support to pgsanity for exactly this reason; ecpg doesn't know about redshift.  Is the syntax really that different?  I guess it doesn't matter how different it is; if it's different at all you'll get a lot of false positives from pgsanity.

**Comment by unicast** [comment]
Ah, ok, got it.
Actually it turns out the main difference is about DDL, e.g. `encode` for columns http://docs.aws.amazon.com/redshift/latest/dg/t_Compressing_data_on_disk.html and system calls like `vacuum delete`, the rest looks fine, thank you!
