### ISSUE TITLE
Adding pgsanity to FreeBSD ports

### ISSUE THREAD

**Issue by 0mp** [markdrago/pgsanity#23]
Hello!

First of all, thank you for pgsanity -> it's a really nice piece of software 👍 

I'm preparing a port of pgsanity for the FreeBSD ports at the moment. Would you find a minute please to create a 0.2.9 tag/release on GitHub so that it is easier to point to the latest version of pgsanity? 

Thanks!

**Comment by markdrago** [comment]
Thanks for your interest in pgsanity.  I'm glad to hear that it's useful for some people.  I merged your README change mentioning the port and created a v0.2.9 tag which should make it easier for you to reference.  Please let me know if there's anything else I can do to help.  Thanks for making it easier for FreeBSD users to adopt pgsanity.

**Comment by 0mp** [comment]
Thanks! It was fun to work on pgsanity. 😄
